[[news]]
date = "2026-03"
content = "Our work on uncertainty-aware continuous remaining useful life prediction was published in IEEE Transactions on Reliability. 🎉"

[[news]]
date = "2025-04"
content = "Our work on robust uncertainty quantification for online remaining useful life prediction was published in Reliability Engineering & System Safety. 🎉"

[[news]]
date = "2024-07"
content = "Our work on diffusion-based data augmentation for aero-engine remaining useful life prediction was published in Reliability Engineering & System Safety. 🎉"
