[[news]]
date = "2026-03"
content = "不确定性感知连续剩余使用寿命预测研究发表于 IEEE Transactions on Reliability。🎉"

[[news]]
date = "2025-04"
content = "面向在线剩余使用寿命预测的鲁棒不确定性量化研究发表于 Reliability Engineering & System Safety。🎉"

[[news]]
date = "2024-07"
content = "基于扩散模型数据增强的航空发动机剩余使用寿命预测研究发表于 Reliability Engineering & System Safety。🎉"
